version: '3'
services:
  qdrant:
    image: qdrant/qdrant
    container_name: test_qdrant
    ports:
      - 6333:6333
    expose:
      - 6333
    volumes:
      - ./qdrant/custom_config.yaml:/qdrant/config/production.yaml
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
